import { fonts } from "./font";
import { Providers } from "./provides";
import { ListingsProvider } from "@/context/ListingsContext";
import "./globals.css";

export const metadata = {
  title: "Obash Signatures",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/favicon.ico"
          type="image/x-icon"
          sizes="16x16"
        ></link>
        <script
          src="https://widget.cloudinary.com/v2.0/global/all.js"
          type="text/javascript"
          async
        ></script>
      </head>
      <body
        className={`${fonts.montserrat.variable} ${fonts.barlowCondensed.variable}`}
      >
        <Providers>
          <ListingsProvider>{children}</ListingsProvider>
        </Providers>
      </body>
    </html>
  );
}
